spring:
  quartz:
    auto-startup: true
    job-store-type: jdbc
    jdbc:
      initialize-schema: embedded
#    properties:
#      org:
#        quartz:
  h2:
    wport: 8000
    port: 8001
    console:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    jdbc-url: jdbc:h2:mem:quartz;MODE=MySQL

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  batch:
    initialize-schema: embedded
